### ISSUE TITLE
OP2 behaviour on overflow

### ISSUE THREAD

**Issue by steinerkelvin** [Kindelia/Kindelia#119]
The current code for evaluating arithmetic OP2 operations is as follows:

```
              ADD => a_u.wrapping_add(b_u) & NUM_MASK,
              SUB => a_u.wrapping_sub(b_u) & NUM_MASK,
              MUL => a_u.wrapping_mul(b_u) & NUM_MASK,
              DIV => a_u.wrapping_div(b_u) & NUM_MASK,
              MOD => a_u.wrapping_rem(b_u) & NUM_MASK,
```

It does wrapping (modular) arithmetic on `u128` and then applies the `NUM_MASK` binary mask (biggest u120 possible).
So, it's doing something like `(a + b) % 2^128 % 2^120` — which is hardly practical semantic for anyone.

I think we should document this as undefined behaviour or adopt one of the following options:

1. Runtime error
2. Stuck computation
    - in practice the same as before — the overflown result is always tainted — but easier to detect/visualize
3. Actually wrapping on u120 (might be useful e.g. hashing)

P.S. I actually don't know how cheap high-level signed integers would be implemented without option 3 but I'm too abstract of a being to wrap my head fully around binary operations and stuff

**Comment by VictorTaelin** [comment]
Oh, you're right. This should be changed to just work as one would expect an U120 would. We should also make that change on HVM, I guess it has the same issue, right?

**Comment by steinerkelvin** [comment]
Oh.. yeah, there is [the same problem](https://github.com/Kindelia/HVM/blob/90bb4ef675f13e48f381e5e63b989002e63330d1/src/runtime.rs#L759) there.  :P

We'll solve this issue here together with #118.

cc @racs4
