### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by han-so1omon** [Kindelia/Kindelia#12]
I am wondering how to use this and is there a public chain to connect to? Thanks!

**Comment by VictorTaelin** [comment]
Not yet, but you can already run a block offline, see notes on: https://github.com/Kindelia/Kindelia/blob/master/example.kdl

We will soon start a test-net, and we'll do extensive testing & quality assessment of the execution environment, as well as finish the paper, before launching the main-net.

**Comment by han-so1omon** [comment]
Nice, I'll try it out. Thanks.

**Comment by locriacyber** [comment]
Is there a plan to run this on top of libp2p (IPFS) pubsub? This would get rid of the discovery problem.

**Comment by developedby** [comment]
> Is there a plan to run this on top of libp2p (IPFS) pubsub? This would get rid of the discovery problem.

You should open a new issue for discussing your sugestion
