### ISSUE TITLE
Unexpected behavior with pattern matching

### ISSUE THREAD

**Issue by MarcusGoldschmidt** [Kindelia/Kindelia#13]
### Describe the bug
When add a new line to a fuction with inner constructor matching, the final result change.

### To Reproduce
Change the main fuction to

```rust
fn main() {
  hvm::test_actions_from_code("
ctr Cons 2
ctr Nil 0

fun Lista 2 {
    !(Lista $(Add x) a) = $(Cons x a)
    !(Lista $(New x #0) list) = $(Cons x list)
} = #0

run {
  $(IONRM !(Lista $(Add #10) $(Nil)) λx
  $(IOEND x))
}
");
}
```

execute `cargo run`

Output

![image](https://user-images.githubusercontent.com/38927366/167847674-ff48a46a-055e-4243-9b91-40cd3487f770.png)

### Expected

See the last line of the output of the run block

![image](https://user-images.githubusercontent.com/38927366/167847864-958675f9-dbba-483c-8b2c-82a79db7c6c1.png)

**Obs:** get expected Result from the code below

```rust
fn main() {
  hvm::test_actions_from_code("
ctr Cons 2
ctr Nil 0

fun Lista 2 {
    !(Lista $(Add x) a) = $(Cons x a)
} = #0

run {
  $(IONRM !(Lista $(Add #10) $(Nil)) λx
  $(IOEND x))
}
");
}
```

### Environment:

Fedora 35
Using Master branch on commit 1987060e

**Comment by VictorTaelin** [comment]
Is it still happening in the current version?

**Comment by MarcusGoldschmidt** [comment]
> Is it still happening in the current version?

Yep, on commit `601ae93d`

```rust
fn main() {
    hvm::test_actions_from_code("
ctr Cons 2
ctr Nil 0
ctr New 2

fun Lista 2 {
    !(Lista $(Add x) a) = $(Cons x a)
    !(Lista $(New x #0) a) = $(Cons x a)
} = #0

run {
    $(IO.done !(Lista $(Add #10) $(Nil)))
}
");
}
```

got

```
Finished dev [unoptimized + debuginfo] target(s) in 0.02s
  Running `target/debug/kindelia`
[Evaluation]
- ctr Cons 2
- ctr Nil 0
- ctr New 2
- fun Lista 2
- run $(IO.done !(Lista $(Add #10) $(Nil)))
    = !(Lista)

[Stats]
- cost: 0 mana (0 rewrites)
- size: 3 words
- time: 0 ms
```

**Comment by VictorTaelin** [comment]
Oh, I didn't understand your question. Kindelia HVM does **not** support nested matches. You need to either split it in different functions, or to use a high level language that compiles to Kindelia HVM.
