### ISSUE TITLE
Refactor `Term` to construct variants with functions

### ISSUE THREAD

**Issue by steinerkelvin** [Kindelia/Kindelia#131]
Check small name on `Term::Fun`, `Term::Num` etc.

Also, deserialization on protocol border should handle big names on direct usage somehow, probably through `Term` construction via the aforementioned functions. I don't know if it's being done already with another way.

**Comment by racs4** [comment]
It should be something like 

```rust
impl Term {
  pub fn fun(name: Name, args: ...) -> Result<Self, String> {
    if name.is_small { Ok(...) }
    else { Err(...) }
  }
}
```
?

And this is not being done.
