### ISSUE TITLE
Allow deploying to any namespace when using `kindelia test`

### ISSUE THREAD

**Issue by developedby** [Kindelia/Kindelia#144]
Since the `test` command doesn't know about who owns what namespace, trying to test any block that deploys to a non-root namespace fails.

**Comment by steinerkelvin** [comment]
Doesn't `test` includes the "genesis" code before running the input? If so, you can deploy on the root namespace signing with the private key 0x01.

**Comment by developedby** [comment]
But I still would need to `reg` manually any sub-namespace I'm using and then sign everything. That's a lot of work if I just want to quickly check if my program is working correctly.

**Comment by steinerkelvin** [comment]
Could you elaborate the use case (example code?)? We can add a flag to enable this.

**Comment by developedby** [comment]
If I'm writing a kind function as well as a small test for it
```
Nic.cool_fun (x: Bool) : Bool
Nic.cool_fun Bool.false = Bool.true
Nic.cool_fun Bool.true = Bool.false

Main {
  Done (Bool.equal (Nic.cool_fun Bool.true) Bool.false)
}
```
Let's say this compiles to the following kindelia code
```
// Nic.cool_fun #Nic.cool_fun (x: (Bool)) : (Bool)
fun (Nic.cool_fun x) {
  (Nic.cool_fun {Bool_false}) = {Bool_true}
  (Nic.cool_fun {Bool_true}) = {Bool_false}
}

// Bool.false #Bool_false : (Bool)
ctr {Bool_false}

// Bool.equal #Bool_equal (a: (Bool)) (b: (Bool)) : (Bool)
fun (Bool_equal a b) {
  (Bool_equal {Bool_true} {Bool_true}) = {Bool_true}
  (Bool_equal {Bool_false} {Bool_false}) = {Bool_true}
  (Bool_equal ~ ~) = {Bool_false}
}

// Bool.true #Bool_true : (Bool)
ctr {Bool_true}

run {
  {Done (Bool_equal (Nic.cool_fun {Bool_true}) {Bool_false})}
}
```
Then I try to test it in kindelia with `kindelia test ...`. I get the error `[fun] Error. Subject '#x000000000000000000000000000000' not allowed to deploy 'Nic.cool_fun'.`

Of course this example is a bit silly, but if my function were some kindelia contract it would make sense for users to want to test it like this.

**Comment by steinerkelvin** [comment]
@developedby 

I have intruduced the flag `--sudo` on `kindelia test` that, besides ignoring storage space limit, also allows deploying in any namespace.

BUT, in my understanding, kind2-kdl compiler should not be generating namespaced names by default, only if explicitly instructed to.

---

P.S.
```
{Done (Bool_equal (Nic.cool_fun {Bool_true}) {Bool_false})}
```
should be
```
(Done (Bool_equal (Nic.cool_fun {Bool_true}) {Bool_false}))
```
or
```
{DONE (Bool_equal (Nic.cool_fun {Bool_true}) {Bool_false})}
```
