### ISSUE TITLE
Division by 0 is not handled

### ISSUE THREAD

**Issue by o-santi** [Kindelia/Kindelia#162]
Currently this contract
```
run {
  (/ #3 #0)
}
```
crashes kindelia, because the division operation is done as is (no checks are made):
```
Div => (*a_u).wrapping_div(*b_u) & NUM_MASK
```
and when `b_u` is 0, `wrapping_div` panics and crashes the whole program. This should be treated somehow, but what should be it's intended behaviour? Not reducing? Some kind of runtime error?

cc @steinerkelvin @VictorTaelin

**Comment by steinerkelvin** [comment]
We'll implement this by simply not reducing `(/ x #0)` but I'll leave the issue here until @VictorTaelin reviews.

**Comment by VictorTaelin** [comment]
We can't simply not reduce it. It should cause the transaction to fail and be reversed, as in out of mana.

**Comment by VictorTaelin** [comment]
Also, we still have the issue of wrapping around 128 bits, not 120 bits, right?

**Comment by steinerkelvin** [comment]
@o-santi  is fixing that rn
