### ISSUE TITLE
The `0` account can be deployed.

### ISSUE THREAD

**Issue by steinerkelvin** [Kindelia/Kindelia#20]
One can deploy a function named `.`, which happens to be encoded to the number `0`, the same that is used as the context for `run` blocks.

```
// The ghost account
// Should this be avoided somehow?

fun . 1 {
  !(. $(Get)) = $(IO.load λx $(IO.done x))
} = #1

run {
  $(IO.call !(. $(Get)) λx $(IO.done x))
}

run {
  $(IO.load λx &{x0 x1} = x; $(IO.save (+ x0 #1) λ~ $(IO.done x1)))
}

run {
  $(IO.call !(. $(Get)) λx $(IO.done x))
}
```

This might be confusing behavior.

**Comment by VictorTaelin** [comment]
Deploying it as an easter egg on the genesis block is my vote

**Comment by quleuber** [comment]
I 100% support that.

But what mischiefs would be coded in that function...

**Comment by VictorTaelin** [comment]
Just return "Be Kind"?

**Comment by steinerkelvin** [comment]
Deploying the empty name was forbidden.

https://github.com/Kindelia/Kindelia/blob/0c55878fac15c185a26f0c2d9eccf2a899ded03b/src/hvm.rs#L1805
