### ISSUE TITLE
Proposal: sugar for single-rule function definion

### ISSUE THREAD

**Issue by quleuber** [Kindelia/Kindelia#44]
```
!(End) = @e @o @i e
```
expands to:
```
!(End) { !(End) = @e @o @i e } = #0
```

**Comment by VictorTaelin** [comment]
We are avoiding syntax sugar bloat on HVM's language, it is not an user-facing language.

**Comment by VictorTaelin** [comment]
Actually, I think a few syntax sugars isn't too bad. I've changed the syntax on https://github.com/Kindelia/Kindelia/commit/0e8d581ce96d91346a0a9f8695189113fde54798. After that is tested, I think we should add that one.

**Comment by VictorTaelin** [comment]
I've removed the need for `=`, but I think `{}` make it more consistent.
