### ISSUE TITLE
tests not working because of memory?

### ISSUE THREAD

**Issue by racs4** [Kindelia/Kindelia#81]
Sometimes doing `cargo test` results in
```
error: test failed, to rerun pass '--bin kindelia'

Caused by:
  process didn't exit successfully: `/Users/rheidner/Documents/Projects/Kindelia/target/debug/deps/kindelia-c19e7b028a190068` (signal: 9, SIGKILL: kill)
```

Although there is no concrete evidence, I think this error happens because of the possible high memory consumption due to the increase of the multiplier of the `HEAP_SIZE` constant to 4096 added to the fact that the tests run in parallel by default. @quleuber commit 2c3f12335c9b2fc23032b15a163c1fce58412e08 drops this number to 64 when not in release mode, but even then this error still happened on his PC. However, with this number at 32 or running the tests sequentially (using `cargo test -- --test-threads=1`) this error does not occur.

**Comment by steinerkelvin** [comment]
@racs4 is this fixed?

**Comment by racs4** [comment]
Yes, `HEAP_SIZE` variable is not used anymore and no memory is pre-allocated like this (the `Nodes` struct, that used this variable to create an array of this size, turns into a `Map`)
