### ISSUE TITLE
Message storm

### ISSUE THREAD

**Issue by steinerkelvin** [Kindelia/Kindelia#83]
Trying to synchronize a local node with the testnet (`quleuber:testnet` branch) is apparently causing a message storm that clogs the node. It apparently receives the same block hundreds of times.

[storm_log.txt](https://github.com/Kindelia/Kindelia/files/8981625/storm_log.txt)

I understand that:
- the local node is asking for the same – or almost the same – block multiple times as it receives the tip from multiple nodes;
- receiving a new tip while it is still receiving the already asked blocks and building the intermediary waiting chain, thus triggering it to ask a block in the middle of the chunk it is already building;
- handling a single PutBlock message is expensive as it always hash the incoming block;
- handing a tip is particularly expensive as it has to traverse the waiting chain;

While understanding the actual cause(s) demands further investigation, I already have some optimizations in mind:
- sleep only the remaining time on each tick;
- preprocess all received messages on a given tick to issue only the necessary commands (add blocks, ask block, etc);
- memoize the association of (know tip –> root of waiting tree), effectively making the aforementioned traversal almost constant cost, only linear on newly added blocks;

cc @racs4

**Comment by VictorTaelin** [comment]
The cause needs to be identified, not optimized away. I can't find the branch to test this.

**Comment by steinerkelvin** [comment]
@racs4 could you write the reproduction steps?

**Comment by VictorTaelin** [comment]
Does https://github.com/Kindelia/Kindelia/commit/01a2a0d3a1c0e678189a57c97382d23cd633a202 solve the issue? If not, decreasing the rate limit solves it? If yes, is overkill? Can we benchmark and come up with a suitable rate limit?

**Comment by racs4** [comment]
> > @racs4 could you write the reproduction steps?
> 
> I only run `cargo run -- start example/block_2.kdl` in [steinerkelvin:testnet](https://github.com/steinerkelvin/Kindelia/tree/testnet) and saved the logs in a file

I made a branch called [racs4:testnet-log](https://github.com/racs4/Kindelia/tree/testnet-log) where I put the prints and functions I used to create the referred log. There is also a script in the `scripts` folder called `testnet-log.sh`. To use it just do `./testnet-log <n>`, where this `<n>` is the number of seconds that the network will be running (it was tested on a Mac). As with any script you need to give authorization with `chmod`.

**Comment by racs4** [comment]
I think that this is fixed after f5a5223b38649d22e6107c86a423600db9a7faf9, that only request missing blocks in gossip requests
